namespace GraphRag.Community;

/// <summary>
/// Represents a hierarchical community summary generated by the GraphRAG pipeline.
/// </summary>
public sealed record CommunityReportRecord(
    string CommunityId,
    int Level,
    IReadOnlyList<string> EntityTitles,
    string Summary,
    IReadOnlyList<string> Keywords);
