# Copyright (c) 2024 Microsoft Corporation.
# Licensed under the MIT License

from .persona import GENERATE_PERSONA_PROMPT
from .entity_types import (
    ENTITY_TYPE_GENERATION_JSON_PROMPT,
    ENTITY_TYPE_GENERATION_PROMPT,
)
from .entity_relationship import (
    ENTITY_RELATIONSHIPS_GENERATION_JSON_PROMPT,
    ENTITY_RELATIONSHIPS_GENERATION_PROMPT,
)

from .domain import GENERATE_DOMAIN_PROMPT

__all__ = [
    "GENERATE_PERSONA_PROMPT",
    "ENTITY_TYPE_GENERATION_JSON_PROMPT",
    "ENTITY_TYPE_GENERATION_PROMPT",
    "ENTITY_RELATIONSHIPS_GENERATION_JSON_PROMPT",
    "ENTITY_RELATIONSHIPS_GENERATION_PROMPT",
    "GENERATE_DOMAIN_PROMPT",
]
