# Copyright (c) 2024 Microsoft Corporation. All rights reserved.
import math

from graphrag.index.graph.extractors.community_reports import sort_context

nan = math.nan


def test_sort_context():
    context: list[dict] = [
        {
            "title": "ALI BABA",
            "degree": 1,
            "node_details": {
                "human_readable_id": 26,
                "title": "ALI BABA",
                "description": "A character from Scrooge's reading, representing a memory of his childhood imagination",
                "degree": 1,
            },
            "edge_details": [
                nan,
                {
                    "human_readable_id": 28,
                    "source": "SCROOGE",
                    "target": "ALI BABA",
                    "description": "Scrooge recalls Ali Baba as a fond memory from his childhood readings",
                    "combined_degree": 32,
                },
            ],
            "claim_details": [nan],
        },
        {
            "title": "BELLE",
            "degree": 1,
            "node_details": {
                "human_readable_id": 31,
                "title": "BELLE",
                "description": "A woman from Scrooge's past, reflecting on how Scrooge's pursuit of wealth changed him and led to the end of their relationship",
                "degree": 1,
            },
            "edge_details": [
                nan,
                {
                    "human_readable_id": 32,
                    "source": "SCROOGE",
                    "target": "BELLE",
                    "description": "Belle and Scrooge were once engaged, but their relationship ended due to Scrooge's growing obsession with wealth",
                    "combined_degree": 32,
                },
            ],
            "claim_details": [nan],
        },
        {
            "title": "CHRISTMAS",
            "degree": 1,
            "node_details": {
                "human_readable_id": 17,
                "title": "CHRISTMAS",
                "description": "A festive season that highlights the contrast between abundance and want, joy and misery in the story",
                "degree": 1,
            },
            "edge_details": [
                nan,
                {
                    "human_readable_id": 23,
                    "source": "SCROOGE",
                    "target": "CHRISTMAS",
                    "description": "Scrooge's disdain for Christmas is a central theme, highlighting his miserliness and lack of compassion",
                    "combined_degree": 32,
                },
            ],
            "claim_details": [nan],
        },
        {
            "title": "CHRISTMAS DAY",
            "degree": 1,
            "node_details": {
                "human_readable_id": 57,
                "title": "CHRISTMAS DAY",
                "description": "The day Scrooge realizes he hasn't missed the opportunity to celebrate and spread joy",
                "degree": 1,
            },
            "edge_details": [
                nan,
                {
                    "human_readable_id": 46,
                    "source": "SCROOGE",
                    "target": "CHRISTMAS DAY",
                    "description": "Scrooge wakes up on Christmas Day with a changed heart, ready to celebrate and spread happiness",
                    "combined_degree": 32,
                },
            ],
            "claim_details": [nan],
        },
        {
            "title": "DUTCH MERCHANT",
            "degree": 1,
            "node_details": {
                "human_readable_id": 19,
                "title": "DUTCH MERCHANT",
                "description": "A historical figure mentioned as having built the fireplace in Scrooge's home, adorned with tiles illustrating the Scriptures",
                "degree": 1,
            },
            "edge_details": [
                nan,
                {
                    "human_readable_id": 25,
                    "source": "SCROOGE",
                    "target": "DUTCH MERCHANT",
                    "description": "Scrooge's fireplace, built by the Dutch Merchant, serves as a focal point in his room where he encounters Marley's Ghost",
                    "combined_degree": 32,
                },
            ],
            "claim_details": [nan],
        },
        {
            "title": "FAN",
            "degree": 1,
            "node_details": {
                "human_readable_id": 27,
                "title": "FAN",
                "description": "Scrooge's sister, who comes to bring him home from school for Christmas, showing a loving family relationship",
                "degree": 1,
            },
            "edge_details": [
                nan,
                {
                    "human_readable_id": 29,
                    "source": "SCROOGE",
                    "target": "FAN",
                    "description": "Fan is Scrooge's sister, who shows love and care by bringing him home for Christmas",
                    "combined_degree": 32,
                },
            ],
            "claim_details": [nan],
        },
        {
            "title": "FRED",
            "degree": 1,
            "node_details": {
                "human_readable_id": 58,
                "title": "FRED",
                "description": "Scrooge's nephew, who invites Scrooge to Christmas dinner, symbolizing family reconciliation",
                "degree": 1,
            },
            "edge_details": [
                nan,
                {
                    "human_readable_id": 47,
                    "source": "SCROOGE",
                    "target": "FRED",
                    "description": "Scrooge accepts Fred's invitation to Christmas dinner, marking a significant step in repairing their relationship",
                    "combined_degree": 32,
                },
            ],
            "claim_details": [nan],
        },
        {
            "title": "GENTLEMAN",
            "degree": 1,
            "node_details": {
                "human_readable_id": 15,
                "title": "GENTLEMAN",
                "description": "Represents charitable efforts to provide for the poor during the Christmas season",
                "degree": 1,
            },
            "edge_details": [
                nan,
                {
                    "human_readable_id": 21,
                    "source": "SCROOGE",
                    "target": "GENTLEMAN",
                    "description": "The gentleman approaches Scrooge to solicit donations for the poor, which Scrooge rebuffs",
                    "combined_degree": 32,
                },
            ],
            "claim_details": [nan],
        },
        {
            "title": "GHOST",
            "degree": 1,
            "node_details": {
                "human_readable_id": 25,
                "title": "GHOST",
                "description": "The Ghost is a spectral entity that plays a crucial role in guiding Scrooge through an introspective journey in Charles Dickens' classic tale. This spirit, likely one of the Christmas spirits, takes Scrooge on a transformative voyage through his past memories, the realities of his present, and the potential outcomes of his future. The purpose of this journey is to make Scrooge reflect deeply on his life, encouraging a profound understanding of the joy and meaning of Christmas. By showing Scrooge scenes from his life, including the potential fate of Tiny Tim, the Ghost rebukes Scrooge for his lack of compassion, ultimately aiming to instill in him a sense of responsibility and empathy towards others. Through this experience, the Ghost seeks to enlighten Scrooge, urging him to change his ways for the better.",
                "degree": 1,
            },
            "edge_details": [
                nan,
                {
                    "human_readable_id": 27,
                    "source": "SCROOGE",
                    "target": "GHOST",
                    "description": "The Ghost is taking Scrooge on a transformative journey by showing him scenes from his past, aiming to make him reflect on his life choices and their consequences. This spectral guide is not only focusing on Scrooge's personal history but also emphasizing the importance of Christmas and the need for a change in perspective. Through these vivid reenactments, the Ghost highlights the error of Scrooge's ways and the significant impact his actions have on others, including Tiny Tim. This experience is designed to enlighten Scrooge, encouraging him to reconsider his approach to life and the people around him.",
                    "combined_degree": 32,
                },
            ],
            "claim_details": [nan],
        },
        {
            "title": "GHOST OF CHRISTMAS PAST",
            "degree": 2,
            "node_details": {
                "human_readable_id": 24,
                "title": "GHOST OF CHRISTMAS PAST",
                "description": "The Ghost of Christmas Past is a spectral figure that plays a significant role in reminding Ebenezer Scrooge of his life's experiences, choices, and their impacts. This spirit, representing Scrooge's past, shows him scenes from his own life, focusing particularly on moments that highlight the joy of Christmas and the consequences of his actions. Through these vivid recollections, the Ghost of Christmas Past serves as a crucial catalyst for Scrooge's journey of self-reflection and transformation, emphasizing the importance of understanding and learning from one's past.",
                "degree": 2,
            },
            "edge_details": [
                nan,
                {
                    "human_readable_id": 14,
                    "source": "EBENEZER SCROOGE",
                    "target": "GHOST OF CHRISTMAS PAST",
                    "description": "The Ghost of Christmas Past is showing Scrooge scenes from his past, including the celebration at Fezziwig's",
                    "combined_degree": 12,
                },
                {
                    "human_readable_id": 26,
                    "source": "SCROOGE",
                    "target": "GHOST OF CHRISTMAS PAST",
                    "description": "The Ghost of Christmas Past visits Scrooge to show him scenes from his past, aiming both to prompt reflection on his life choices and to remind him of the joy of Christmas. This spectral visitor plays a crucial role in Scrooge's journey, offering him a unique perspective on his own history and the opportunities he missed for happiness and fulfillment. Through this encounter, Scrooge is encouraged to reconsider the path he has taken and the impact of his actions on himself and others, with a particular emphasis on the spirit and true meaning of Christmas.",
                    "combined_degree": 33,
                },
            ],
            "claim_details": [nan],
        },
        {
            "title": "GHOST OF CHRISTMAS PRESENT",
            "degree": 2,
            "node_details": {
                "human_readable_id": 32,
                "title": "GHOST OF CHRISTMAS PRESENT",
                "description": "The Ghost of Christmas Present is a spirit that plays a crucial role in Charles Dickens' \"A Christmas Carol\" by accompanying Ebenezer Scrooge on a transformative journey. This spirit represents the current Christmas and is tasked with showing Scrooge various scenes of joy, kindness, and community associated with the holiday. Through its guidance, Scrooge is exposed to both the celebrations of the season and the hardships faced by those less fortunate. The Ghost of Christmas Present's purpose is to instill in Scrooge a sense of joy, compassion, and a deep understanding of the value of community, thereby encouraging him to embrace the spirit of Christmas and reconsider his miserly ways.",
                "degree": 2,
            },
            "edge_details": [
                {
                    "human_readable_id": 52,
                    "source": "GHOST OF CHRISTMAS PRESENT",
                    "target": "TINY TIM",
                    "description": "Tiny Tim's situation is highlighted by the Ghost of Christmas Present to teach Scrooge about compassion and the impact of his actions",
                    "combined_degree": 7,
                },
                {
                    "human_readable_id": 33,
                    "source": "SCROOGE",
                    "target": "GHOST OF CHRISTMAS PRESENT",
                    "description": "Scrooge, as part of his journey towards understanding the meaning of Christmas, is visited by the Ghost of Christmas Present. This spectral guide plays a crucial role in leading Scrooge to understand and embrace the spirit of Christmas, which ultimately contributes to his transformation. By showing Scrooge the joy and kindness of Christmas through various celebrations, the Ghost of Christmas Present helps illuminate the true essence of the holiday for him. This experience is pivotal in changing Scrooge's perspective and attitude towards Christmas, guiding him from a state of miserliness and indifference to one of generosity and warmth.",
                    "combined_degree": 33,
                },
            ],
            "claim_details": [nan],
        },
        {
            "title": "GREAT BRITAIN",
            "degree": 1,
            "node_details": {
                "human_readable_id": 33,
                "title": "GREAT BRITAIN",
                "description": "The setting of the story, implied through the mention of its climate and towns",
                "degree": 1,
            },
            "edge_details": [
                nan,
                {
                    "human_readable_id": 34,
                    "source": "SCROOGE",
                    "target": "GREAT BRITAIN",
                    "description": "Scrooge lives and experiences his transformative journey in Great Britain",
                    "combined_degree": 32,
                },
            ],
            "claim_details": [nan],
        },
        {
            "title": "IGNORANCE",
            "degree": 1,
            "node_details": {
                "human_readable_id": 46,
                "title": "IGNORANCE",
                "description": "A boy representing ignorance, warned by the Spirit to be particularly dangerous for the future",
                "degree": 1,
            },
            "edge_details": [
                nan,
                {
                    "human_readable_id": 39,
                    "source": "SCROOGE",
                    "target": "IGNORANCE",
                    "description": "Ignorance is presented to Scrooge by the Spirit as a warning",
                    "combined_degree": 32,
                },
            ],
            "claim_details": [nan],
        },
        {
            "title": "LONDON",
            "degree": 1,
            "node_details": {
                "human_readable_id": 16,
                "title": "LONDON",
                "description": "The city where the story is set, characterized by its fog, cold, and the socio-economic conditions of the time",
                "degree": 1,
            },
            "edge_details": [
                nan,
                {
                    "human_readable_id": 22,
                    "source": "SCROOGE",
                    "target": "LONDON",
                    "description": "Scrooge lives and works in London, which sets the scene for his interactions and experiences",
                    "combined_degree": 32,
                },
            ],
            "claim_details": [nan],
        },
        {
            "title": "MARLEY",
            "degree": 2,
            "node_details": {
                "human_readable_id": 10,
                "title": "MARLEY",
                "description": "Jacob Marley is the deceased business partner of Ebenezer Scrooge in \"A Christmas Carol.\" Marley died seven years ago on Christmas Eve and is a pivotal character in the story, despite his death. He is most memorably known for his ghostly appearance to Scrooge, initially manifesting as a spectral face on Scrooge's door knocker. This eerie encounter marks the beginning of Scrooge's transformative journey, guided by the spirits. Marley's role is to warn Scrooge of the impending visits by three spirits and to urge him to change his ways, thus avoiding Marley's own fate of wandering the Earth bound in heavy chains as punishment for his greed andselfishness in life.",
                "degree": 2,
            },
            "edge_details": [
                {
                    "human_readable_id": 17,
                    "source": "MARLEY",
                    "target": "SCROOGE",
                    "description": "Marley was Scrooge's business partner before he passed away, and his ghostly appearance signifies the beginning of Scrooge's supernatural journey.",
                    "combined_degree": 33,
                },
                {
                    "human_readable_id": 7,
                    "source": "EBENEZER SCROOGE",
                    "target": "MARLEY",
                    "description": "Ebenezer Scrooge was the businesspartner of Jacob Marley in A Christmas Carol",
                    "combined_degree": 12,
                },
            ],
            "claim_details": [nan],
        },
        {
            "title": "MARLEY'S GHOST",
            "degree": 1,
            "node_details": {
                "human_readable_id": 18,
                "title": "MARLEY'S GHOST",
                "description": "Marley's Ghost is the spectral presence of Jacob Marley, the former business partner of Ebenezer Scrooge. This ghostly figure visits Scrooge to deliver a grave warning about Scrooge's future, emphasizing the opportunity for Scrooge to change his ways and avoid Marley's own dismal fate. Marley's Ghost forewarns of the impending visitations by three spirits, presenting these as a chance for Scrooge to escape the chains Marley himself is bound by due to his life's misdeeds. This visitation sets the stage for Scrooge's journey of self-discovery and redemption.",
                "degree": 1,
            },
            "edge_details": [
                nan,
                {
                    "human_readable_id": 24,
                    "source": "SCROOGE",
                    "target": "MARLEY'S GHOST",
                    "description": "Marley's Ghost visits Scrooge to warn him about his future and to reflect on his past actions. During this visitation, Marley's Ghost also warns Scrooge of the upcoming visitation by the Ghost of Christmas Past. This encounter is presented as part of Scrooge's opportunity for redemption, indicating that Marley's Ghost plays a crucial role in initiating Scrooge's journey towardsself-improvement and understanding the consequences of his actions.",
                    "combined_degree": 32,
                },
            ],
            "claim_details": [nan],
        },
        {
            "title": "PHANTOM",
            "degree": 1,
            "node_details": {
                "human_readable_id": 49,
                "title": "PHANTOM",
                "description": "PHANTOM is a spectral figure that guides Scrooge through various scenes, symbolizing his conscience or future, and to impart moral lessons. This entity plays a crucial role in presenting different aspectsof Scrooge's life, aiming to evoke a transformation by confronting him with the consequences of his actions and the importance of compassion and change.",
                "degree": 1,
            },
            "edge_details": [
                nan,
                {
                    "human_readable_id": 42,
                    "source": "SCROOGE",
                    "target": "PHANTOM",
                    "description": "The Phantom guides Scrooge through various scenes with the purpose of teaching him about the consequences of his actions and making him reflect on his life. This journey is designed to provide Scrooge with a comprehensive understanding of the impact of his behavior on himself and others, encouraging a deep reflection on his life choices.",
                    "combined_degree": 32,
                },
            ],
            "claim_details": [nan],
        },
        {
            "title": "PORTLY GENTLEMEN",
            "degree": 1,
            "node_details": {
                "human_readable_id": 14,
                "title": "PORTLY GENTLEMEN",
                "description": "Pleasant gentlemen who visit Scrooge to collect donations for thepoor and destitute during the festive season",
                "degree": 1,
            },
            "edge_details": [
                nan,
                {
                    "human_readable_id": 20,
                    "source": "SCROOGE",
                    "target": "PORTLY GENTLEMEN",
                    "description": "The gentlemen approach Scrooge for a donation to help the poor, but Scrooge is uncooperative",
                    "combined_degree": 32,
                },
            ],
            "claim_details": [nan],
        },
        {
            "title": "SCROOGE",
            "degree": 31,
            "node_details": {
                "human_readable_id": 11,
                "title": "SCROOGE",
                "description": "Ebenezer Scrooge is a central character known for his initial portrayal as a miserly, unkind, and cold-hearted individual, described as a \"squeezing, wrenching, grasping, scraping, clutching, covetous old sinner, hard and sharp as flint,\" with a solitary nature and a disdain for the festive season and a lack of compassion for the poor. His life is marked by a significant transformation, catalyzed by a series of ghostly visitations that challenge his perspectives and attitudes towards life, particularly his disdain for Christmas and his lack of compassion towards others. These visitations begin with the ghost of his former partner, Marley, and are followed by other spirits who guide him through various scenes to reflect on his life's choices, the consequences of his actions, and the impact of his pursuit of wealth on his relationships.\n\nThroughout the story, Scrooge is depicted as reflecting on his past, showing regret and an emotional response to his memories. He is tormented by spirits, leading him to reconsider the joy of Christmas and the importance of compassion. Initially resistant to the Christmas spirit, Scrooge undergoes a profound transformation, becoming generous and kind, especially towards his employee, Bob Cratchit, and Tiny Tim. This change is not only a shift in his attitude towards life and others but also a reflection on the impact of death and the importance of relationships over wealth.\n\nScrooge's journey from a man who disbelieves in the joy of Christmas to one who embodies the spirit of the season is marked by his interactions with various spirits and the influence of his nephew. These experiences soften his miserly ways and lead him to embrace a new perspective on life, characterized by generosity, kindness, and a newfound appreciation for the Christmas spirit. Through this transformation, Scrooge becomes a symbol of redemption and the power of change, ultimately reflecting on the consequences of his actions and showing a significant change of heart regarding Christmas, generosity, and the value of compassion towards others.",
                "degree": 31,
            },
            "edge_details": [
                {
                    "human_readable_id": 18,
                    "source": "SCROOGE",
                    "target": "SCROOGE'S NEPHEW",
                    "description": "Scrooge's nephew is steadfast in his determination to share the joy of Christmas with his uncle, Scrooge, despite the latter's initial reluctance and dismissive attitude towards his nephew's Christmas cheer and invitation. The nephew, being Scrooge's family, remains persistent in his efforts to spread holiday joy and warmth to his uncle, hoping to change Scrooge's cold demeanor and embrace the festive spirit together.",
                    "combined_degree": 34,
                },
                {
                    "human_readable_id": 19,
                    "source": "SCROOGE",
                    "target": "SCROOGE'S CLERK",
                    "description": "Scrooge employs the clerk, keeps him in poor working conditions, and pays hima low wage",
                    "combined_degree": 32,
                },
                {
                    "human_readable_id": 20,
                    "source": "SCROOGE",
                    "target": "PORTLY GENTLEMEN",
                    "description": "The gentlemen approach Scrooge for a donation to help the poor, but Scrooge is uncooperative",
                    "combined_degree": 32,
                },
                {
                    "human_readable_id": 21,
                    "source": "SCROOGE",
                    "target": "GENTLEMAN",
                    "description": "The gentleman approaches Scrooge to solicit donations for the poor, which Scrooge rebuffs",
                    "combined_degree": 32,
                },
                {
                    "human_readable_id": 22,
                    "source": "SCROOGE",
                    "target": "LONDON",
                    "description": "Scrooge lives and works in London, which sets the scene for his interactions and experiences",
                    "combined_degree": 32,
                },
                {
                    "human_readable_id": 23,
                    "source": "SCROOGE",
                    "target": "CHRISTMAS",
                    "description": "Scrooge's disdain for Christmas is a central theme, highlighting his miserliness and lack of compassion",
                    "combined_degree": 32,
                },
                {
                    "human_readable_id": 24,
                    "source": "SCROOGE",
                    "target": "MARLEY'S GHOST",
                    "description": "Marley's Ghost visits Scrooge to warn him about his future and to reflect on his past actions. During this visitation, Marley's Ghost also warns Scrooge of the upcoming visitation by the Ghost of Christmas Past. This encounter is presented as part of Scrooge's opportunity for redemption, indicating that Marley's Ghost plays a crucial role in initiating Scrooge's journey towards self-improvement and understanding the consequences of his actions.",
                    "combined_degree": 32,
                },
                {
                    "human_readable_id": 25,
                    "source": "SCROOGE",
                    "target": "DUTCH MERCHANT",
                    "description": "Scrooge's fireplace, built by the Dutch Merchant, serves as a focal point in his room where he encounters Marley's Ghost",
                    "combined_degree": 32,
                },
                {
                    "human_readable_id": 26,
                    "source": "SCROOGE",
                    "target": "GHOST OF CHRISTMAS PAST",
                    "description": "The Ghost of Christmas Past visits Scrooge to show him scenes from his past, aiming both to prompt reflection on his life choices and to remind him of the joy of Christmas. This spectral visitor plays a crucial role in Scrooge's journey, offering him a unique perspective on his own history and the opportunities he missed for happiness and fulfillment. Through this encounter, Scrooge is encouraged to reconsider the path he has taken and the impact of his actions on himself and others, with a particular emphasis on the spirit and true meaning of Christmas.",
                    "combined_degree": 33,
                },
                {
                    "human_readable_id": 27,
                    "source": "SCROOGE",
                    "target": "GHOST",
                    "description": "The Ghost is taking Scrooge on a transformative journey by showing him scenes from his past, aiming to make him reflect on his life choices and their consequences. This spectral guide is not only focusing on Scrooge's personal history but also emphasizing the importance of Christmas and the need for a change in perspective. Through these vivid reenactments, the Ghost highlights the error of Scrooge's ways and the significant impact his actions have on others, including Tiny Tim. This experience is designed to enlighten Scrooge, encouraging him to reconsider his approach to life and the people around him.",
                    "combined_degree": 32,
                },
                {
                    "human_readable_id": 28,
                    "source": "SCROOGE",
                    "target": "ALI BABA",
                    "description": "Scrooge recalls Ali Baba as a fond memory from his childhood readings",
                    "combined_degree": 32,
                },
                {
                    "human_readable_id": 29,
                    "source": "SCROOGE",
                    "target": "FAN",
                    "description": "Fan is Scrooge's sister, who shows love and care by bringing him home for Christmas",
                    "combined_degree": 32,
                },
                {
                    "human_readable_id": 30,
                    "source": "SCROOGE",
                    "target": "FEZZIWIG",
                    "description": "Fezziwig is remembered by Scrooge as a kind and generous employer during his apprenticeship",
                    "combined_degree": 35,
                },
                {
                    "human_readable_id": 31,
                    "source": "SCROOGE",
                    "target": "DICK WILKINS",
                    "description": "Dick Wilkins was a close friend to Scrooge during their apprenticeship under Fezziwig",
                    "combined_degree": 34,
                },
                {
                    "human_readable_id": 32,
                    "source": "SCROOGE",
                    "target": "BELLE",
                    "description": "Belle and Scrooge were once engaged, but their relationship ended due to Scrooge's growing obsession with wealth",
                    "combined_degree": 32,
                },
                {
                    "human_readable_id": 33,
                    "source": "SCROOGE",
                    "target": "GHOST OF CHRISTMAS PRESENT",
                    "description": "Scrooge, as part of his journey towards understanding the meaning of Christmas, is visited by the Ghost of Christmas Present. This spectral guide plays a crucial role in leading Scrooge to understand and embrace the spirit of Christmas, which ultimately contributes to his transformation. By showing Scrooge the joy and kindness of Christmas through various celebrations, the Ghost of Christmas Present helps illuminate the true essence of the holiday for him. This experience is pivotal in changing Scrooge's perspective and attitude towards Christmas, guiding him from a state of miserliness and indifference to one of generosity and warmth.",
                    "combined_degree": 33,
                },
                {
                    "human_readable_id": 34,
                    "source": "SCROOGE",
                    "target": "GREAT BRITAIN",
                    "description": "Scrooge lives and experiences his transformative journey in Great Britain",
                    "combined_degree": 32,
                },
                {
                    "human_readable_id": 35,
                    "source": "SCROOGE",
                    "target": "BOB CRATCHIT",
                    "description": "Scrooge, who is Bob Cratchit's employer, undergoes a significant transformation that profoundly impacts the Cratchit family's future. Initially indifferent to the hardships faced by Cratchit's family, Scrooge decides to raise Bob Cratchit's salary and assist his family as a gesture of his newfound generosity. This change in Scrooge's character is acknowledged by Bob, who refers to him as the \"Founder of the Feast,\" despite Mrs. Cratchit's disdain for Scrooge's previous demeanor. The promise to increase Bob Cratchit's salary and assist his family underscores a direct and evolving relationship between employer and employee, marked by a newfound commitment to welfare and support. This transformation in Scrooge not only alters his interactions with Bob Cratchit but also promises a brighter future for the Cratchit family, illustrating the profound effect of personal change on the lives of others.",
                    "combined_degree": 35,
                },
                {
                    "human_readable_id": 36,
                    "source": "SCROOGE",
                    "target": "TINY TIM",
                    "description": "Scrooge undergoes a profound transformation, becoming a benefactor and like a second father to Tiny Tim. This change in Scrooge is significantly inspired by Tiny Tim's condition and his family's situation, leading to a personal and caring relationship between the two. Scrooge ensures that Tiny Tim does not die, reflecting the depth of his transformation and the positive impact it has on Tiny Tim's life. This development showcases the strong bond that forms between Scrooge and Tiny Tim, stemming from Scrooge's newfound generosity and compassion.",
                    "combined_degree": 36,
                },
                {
                    "human_readable_id": 37,
                    "source": "SCROOGE",
                    "target": "SCROOGE'S NIECE",
                    "description": "Scrooge's niece is participating in Christmas celebrations that Scrooge's nephew hopes will influence Scrooge positively",
                    "combined_degree": 34,
                },
                {
                    "human_readable_id": 38,
                    "source": "SCROOGE",
                    "target": "SPIRIT",
                    "description": "The Spirit is showing Scrooge various scenes to teach him moral lessons",
                    "combined_degree": 32,
                },
                {
                    "human_readable_id": 39,
                    "source": "SCROOGE",
                    "target": "IGNORANCE",
                    "description": "Ignorance is presented to Scrooge by the Spirit as a warning",
                    "combined_degree": 32,
                },
                {
                    "human_readable_id": 40,
                    "source": "SCROOGE",
                    "target": "WANT",
                    "description": "Want is presented to Scrooge by the Spirit as a warning",
                    "combined_degree": 32,
                },
                {
                    "human_readable_id": 41,
                    "source": "SCROOGE",
                    "target": "GHOST OF CHRISTMAS YET TO COME",
                    "description": "The Ghost of Christmas Yet to Come is guiding Scrooge through visions of the future",
                    "combined_degree": 33,
                },
                {
                    "human_readable_id": 42,
                    "source": "SCROOGE",
                    "target": "PHANTOM",
                    "description": "The Phantom guides Scrooge through various scenes with the purpose of teaching him about the consequences of his actions and making him reflect on his life. This journey is designed to provide Scrooge with a comprehensive understanding of the impact of his behavior on himself and others, encouraging a deep reflection on his life choices.",
                    "combined_degree": 32,
                },
                {
                    "human_readable_id": 43,
                    "source": "SCROOGE",
                    "target": "OLD JOE",
                    "description": "Old Joe is seen evaluating items that once belonged to Scrooge, suggesting a posthumous connection",
                    "combined_degree": 33,
                },
                {
                    "human_readable_id": 44,
                    "source": "SCROOGE",
                    "target": "MRS. DILBER",
                    "description": "Mrs. Dilber is involved in selling Scrooge's possessions after his death, indicating a connection to him",
                    "combined_degree": 33,
                },
                {
                    "human_readable_id": 45,
                    "source": "SCROOGE",
                    "target": "DEATH",
                    "description": "Scrooge is confronted with the concept of death, leading to a significant change in his outlook",
                    "combined_degree": 33,
                },
                {
                    "human_readable_id": 46,
                    "source": "SCROOGE",
                    "target": "CHRISTMAS DAY",
                    "description": "Scrooge wakes up on Christmas Day with a changed heart, ready to celebrate and spread happiness",
                    "combined_degree": 32,
                },
                {
                    "human_readable_id": 47,
                    "source": "SCROOGE",
                    "target": "FRED",
                    "description": "Scrooge accepts Fred's invitation to Christmas dinner, marking a significant step in repairing their relationship",
                    "combined_degree": 32,
                },
                {
                    "human_readable_id": 17,
                    "source": "MARLEY",
                    "target": "SCROOGE",
                    "description": "Marley was Scrooge's business partner before he passed away, and his ghostly appearance signifies the beginning of Scrooge's supernatural journey.",
                    "combined_degree": 33,
                },
            ],
            "claim_details": [
                {
                    "human_readable_id": 2.0,
                    "subject_id": "SCROOGE",
                    "type": "LACK OF EMPATHY AND GENEROSITY",
                    "status": "TRUE",
                    "description": "Scrooge exhibits a significant lack of empathy and generosity, particularly highlighted by his disdain for Christmas and the welfare of the poor and his clerk. He expresses no interest in the well-being of others, preferring to hoard his wealth and maintain his miserly ways",
                },
                {
                    "human_readable_id": 4.0,
                    "subject_id": "SCROOGE",
                    "type": "POOR WORKING CONDITIONS",
                    "status": "TRUE",
                    "description": "Scrooge subjects his clerk to poor working conditions, keeping him in a cold, dismal office with inadequate heating, reflecting Scrooge's lack of care for his employee's comfort and well-being",
                },
                {
                    "human_readable_id": 5.0,
                    "subject_id": "SCROOGE",
                    "type": "LACK OF CHARITABLE SPIRIT",
                    "status": "TRUE",
                    "description": "Scrooge expressed a lack of charitable spirit and concern for the poor and destitute during a conversation with a gentleman seeking donations for the poor at Christmas, indicating a preference for the poor to utilize existing institutionslike prisons and workhouses rather than receiving direct aid",
                },
                {
                    "human_readable_id": 6.0,
                    "subject_id": "SCROOGE",
                    "type": "UNFAIR LABOR PRACTICES",
                    "status": "TRUE",
                    "description": "Scrooge displayed unfair labor practices by begrudgingly allowing his clerk, Bob Cratchit, a single day off for Christmas, indicating a lack of empathy and fairness towards his employee's well-being and holiday rights",
                },
                {
                    "human_readable_id": 12.0,
                    "subject_id": "SCROOGE",
                    "type": "PERSONAL REGRET AND REFLECTION",
                    "status": "TRUE",
                    "description": "Scrooge undergoes a profound personal reflection and regret regarding his past actions and the impact of Fezziwig's kindness. This reflection is triggered by witnessing the joy and generosity of Fezziwig, leading Scrooge to wish he could express kindness to his own clerk, Bob Cratchit, in the present.",
                },
                {
                    "human_readable_id": 13.0,
                    "subject_id": "SCROOGE",
                    "type": "TRANSFORMATION AND REALIZATION",
                    "status": "TRUE",
                    "description": "Scrooge's interaction with the Ghost of Christmas Past leads to a realization about the importance of kindness and the negative impact of his greed. This marks the beginning of his transformation, as he starts to understand the value of human connections over wealth.",
                },
                {
                    "human_readable_id": 25.0,
                    "subject_id": "SCROOGE",
                    "type": "FINANCIAL SUPPORT",
                    "status": "TRUE",
                    "description": "Scrooge promised to raise Bob Cratchit's salary and assist his struggling family, discussing affairs over a Christmas bowl of smoking bishop",
                },
                {
                    "human_readable_id": 26.0,
                    "subject_id": "SCROOGE",
                    "type": "HEALTH SUPPORT",
                    "status": "TRUE",
                    "description": "Scrooge became a second father to Tiny Tim, who did not die as a result",
                },
                {
                    "human_readable_id": 27.0,
                    "subject_id": "SCROOGE",
                    "type": "PERSONAL TRANSFORMATION",
                    "status": "TRUE",
                    "description": "Scrooge was better than his word, becoming a good friend, master, and man, with a significant alteration in his behavior observed by others",
                },
            ],
        },
        {
            "title": "SCROOGE'S CLERK",
            "degree": 1,
            "node_details": {
                "human_readable_id": 13,
                "title": "SCROOGE'S CLERK",
                "description": "Scrooge's clerk works in a dismal little cell, has a very small fire to keep warm, and is underpaid",
                "degree": 1,
            },
            "edge_details": [
                nan,
                {
                    "human_readable_id": 19,
                    "source": "SCROOGE",
                    "target": "SCROOGE'S CLERK",
                    "description": "Scrooge employs the clerk, keeps him in poor working conditions, and pays him a low wage",
                    "combined_degree": 32,
                },
            ],
            "claim_details": [nan],
        },
        {
            "title": "SPIRIT",
            "degree": 1,
            "node_details": {
                "human_readable_id": 45,
                "title": "SPIRIT",
                "description": "A sorrowful spirit showing Scrooge various scenesto impart moral lessons",
                "degree": 1,
            },
            "edge_details": [
                nan,
                {
                    "human_readable_id": 38,
                    "source": "SCROOGE",
                    "target": "SPIRIT",
                    "description": "The Spirit is showing Scrooge various scenes to teach him moral lessons",
                    "combined_degree": 32,
                },
            ],
            "claim_details": [nan],
        },
        {
            "title": "WANT",
            "degree": 1,
            "node_details": {
                "human_readable_id": 47,
                "title": "WANT",
                "description": "A girl representing want or poverty, shown alongside Ignorance as a warning by the Spirit",
                "degree": 1,
            },
            "edge_details": [
                nan,
                {
                    "human_readable_id": 40,
                    "source": "SCROOGE",
                    "target": "WANT",
                    "description": "Want is presented to Scrooge by the Spirit as a warning",
                    "combined_degree": 32,
                },
            ],
            "claim_details": [nan],
        },
    ]

    ctx = sort_context(context)
    assert ctx is not None
