name: General Issue
description: File a general issue
title: "[Issue]: <title> "
labels: ["triage"]

body:
  - type: textarea
    id: description
    attributes:
      label: Describe the issue
      description: A clear and concise description of what the issue is.
      placeholder: What went wrong?
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: |
        Steps to reproduce the behavior:

        1. Step 1
        2. Step 2
        3. ...
        4. See error
      placeholder: How can we replicate the issue?
  - type: textarea
    id: configused
    attributes:
      label: GraphRAG Config Used
      description: The GraphRAG configuration used for the run.
      placeholder: The settings.yaml content or GraphRAG configuration
  - type: textarea
    id: screenshotslogs
    attributes:
      label: Logs and screenshots
      description: If applicable, add screenshots and logs to help explain your problem.
      placeholder: Add logs and screenshots here
  - type: textarea
    id: additional_information
    attributes:
      label: Additional Information
      description: |
        - GraphRAG Version: e.g., v0.1.1
        - Operating System: e.g., Windows 10, Ubuntu 20.04
        - Python Version: e.g., 3.8
        - Related Issues: e.g., #1
        - Any other relevant information.
      value: |
        - GraphRAG Version:
        - Operating System:
        - Python Version:
        - Related Issues:
